# Generated by Django 2.0.5 on 2018-06-03 05:44

import GuestListWS.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this family member', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the family member', max_length=200)),
                ('food_choice', models.CharField(choices=[('Chicken', 'Chicken'), ('Pork', 'Pork'), ('Ravioli', 'Ravioli'), ('Child', 'Kid'), ('Not Needed', 'Not Needed')], default='Chicken', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this guest', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Guest Name', max_length=200)),
                ('address', models.CharField(help_text='Guest Address', max_length=300)),
                ('city', models.CharField(help_text='Guest city', max_length=300)),
                ('state', models.CharField(help_text='Guest state', max_length=300)),
                ('zip_code', models.CharField(help_text='The zip code', max_length=10)),
                ('country', models.CharField(default='USA', help_text='Guest country', max_length=300)),
                ('rsvp', models.DateField(blank=True, help_text='The date the guest sent rsvp', null=True)),
                ('rsvp_url', models.CharField(default=GuestListWS.models.generate_url, help_text='URL to use when submitting RSVP', max_length=7, unique=True)),
                ('will_attend', models.BooleanField(default=False, help_text='Will guest attend')),
            ],
        ),
        migrations.AddField(
            model_name='familymember',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familymember', to='GuestListWS.Guest'),
        ),
    ]
